# Generated by Django 4.2.4 on 2023-08-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceassignment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
